from bst import *
tree=BST()
# tree.insert(20)
# tree.insert(40)
# tree.insert(10)
# tree.insert(30)
# tree.insert(70)
# tree.insert(15)
# tree.insert(65)
# print(tree.search(4),tree.search(4).data)
# print(tree.search(4),tree.search(3).data)
# print(tree.search(4),tree.search(2).data)
# print(tree.search(4),tree.search(1).data)
# print(tree.search(4),tree.search(6).data)
# print(tree.search(9))
tree.createTreeFromList([1,2,3,4,5,6,7,8,9,9,9,9])
# tree.delete(40)
tree.printTree()
print(tree.lca(3,1))
print(tree.isBST())
